function importedFileRx = importfileRX(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   HELIUMRXCAM00 = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   HELIUMRXCAM00 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   heliumRxCAM00 = importfile('heliumRxCAM_00.log', 1, 35929);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/02/21 18:36:09

%% Initialize variables.
delimiter = ';';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: categorical (%C)
%	column2: categorical (%C)
%   column3: double (%f)
%	column4: categorical (%C)
%   column5: categorical (%C)
%	column6: double (%f)
%   column7: categorical (%C)
%	column8: double (%f)
%   column9: categorical (%C)
%	column10: double (%f)
%   column11: categorical (%C)
%	column12: double (%f)
%   column13: categorical (%C)
%	column14: double (%f)
%   column15: categorical (%C)
%	column16: double (%f)
%   column17: categorical (%C)
%	column18: double (%f)
%   column19: categorical (%C)
%	column20: double (%f)
%   column21: categorical (%C)
%	column22: double (%f)
%   column23: categorical (%C)
%	column24: double (%f)
%   column25: categorical (%C)
%	column26: double (%f)
%   column27: categorical (%C)
%	column28: double (%f)
%   column29: categorical (%C)
%	column30: double (%f)
%   column31: categorical (%C)
%	column32: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%C%C%f%C%C%f%C%f%C%f%C%f%C%f%C%f%C%f%C%f%C%f%C%f%C%f%C%f%C%f%C%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
importedFile = table(dataArray{1:end-1}, 'VariableNames', {'RX','MAC','VarName3','RXCAM','Validation','VarName6','Protocol','VarName8','StationID','VarName10','GenDeltaTime','VarName12','SeqNum','VarName14','Lon','VarName16','Lat','VarName18','Speed','VarName20','SpeedConf','VarName22','Heading','VarName24','CurrentLon','VarName26','CurrentLat','VarName28','CurrentSpeed','VarName30','CurrentTime','VarName32'});

